markdown: redcarpet

permalink: /:categories/:title.html

url: 

lsi: false

pygments: true

safe: true

auto: false 



paginate: 8

paginate_path: "page:num"



# presonal config

domain: nyanyanyan.github.io

title: Kurisu

description: 
author: nyanyanyan

email: winfirm#163.com

github: nyanyanyan


config:
  js_dir:
  img_dir:
  css_dir:
